[pytest]
DJANGO_SETTINGS_MODULE = my_project.settings
<<<<<<< HEAD
python_files = tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
django_db_setup = django_db_setup
addopts = --reuse-db --nomigrations
=======
python_files           = tests.py test_*.py *_test.py
python_classes         = Test*
python_functions       = test_*
>>>>>>> 4bb96d94630885ef9a3f71df8235846a7bfa7d41
