# Generated by Django 5.2.1 on 2026-04-21 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iles_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsupervisor',
            name='phone_number',
            field=models.CharField(help_text='Format: +256XXXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +256700000000', regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('academic_supervisor', 'Academic Supervisor'), ('workplace_supervisor', 'Workplace Supervisor'), ('administrator', 'Administrator')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='iles_users_perms', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='workplacesupervisor',
            name='phone_number',
            field=models.CharField(help_text='Format: +256XXXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +256700000000', regex='^\\+256\\d{9}$')]),
        ),
    ]
