# Generated by Django 6.0.3 on 2026-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
