# Generated by Django 5.2.1 on 2026-04-18 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Issue', 'verbose_name_plural': 'Student Issues'},
        ),
        migrations.AlterField(
            model_name='academicsupervisor',
            name='phone_number',
            field=models.CharField(help_text='Format: +256XXXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +256700000000', regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='workplacesupervisor',
            name='phone_number',
            field=models.CharField(help_text='Format: +256XXXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +256700000000', regex='^\\+256\\d{9}$')]),
        ),
    ]
