# Generated by Django 6.0.3 on 2026-03-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iles_models_app.academic_supervisor'),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='internship_administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iles_models_app.internship_administrator'),
        ),
        migrations.AlterField(
            model_name='internship_placement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iles_models_app.workplace_supervisor'),
        ),
    ]
