# Generated by Django 5.2.1 on 2026-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_alter_logbookentry_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
