# Generated by Django 5.2.1 on 2026-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_issue_is_approved_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
