# Generated by Django 6.0.3 on 2026-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_alter_academic_supervisor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook_entry',
            name='challenges',
            field=models.TextField(default='None'),
        ),
    ]
