# Generated by Django 5.2.1 on 2026-05-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_alter_logbookentry_options_alter_user_role_and_more'),
        ('iles_models_app', '0002_issue_is_approved_alter_user_role_and_more'),
    ]

    operations = [
    ]
