# Generated by Django 5.2.1 on 2026-05-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_alter_issue_options_and_more'),
        ('iles_models_app', '0003_user_is_approved'),
    ]

    operations = [
    ]
