# Generated by Django 5.2.1 on 2026-05-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0003_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_approved',
        ),
    ]
