# Generated by Django 6.0.3 on 2026-04-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0003_issue_end_date_issue_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='week_number',
        ),
    ]
