# Generated by Django 5.2.1 on 2026-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles_models_app', '0002_alter_logbookentry_options_issue_is_approved_and_more'),
        ('iles_models_app', '0004_merge_20260507_0227'),
        ('iles_models_app', '0004_merge_20260508_0816'),
        ('iles_models_app', '0004_remove_issue_is_approved'),
    ]

    operations = [
    ]
